import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

interface PDFData {
  toolName: string;
  inputs: Record<string, any>;
  outputs: Record<string, any>;
}

export function generateProFormaPDF(data: PDFData) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  let yPosition = 20;

  doc.setFillColor(30, 41, 59);
  doc.rect(0, 0, pageWidth, 40, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text('Property Launch Pad', pageWidth / 2, 20, { align: 'center' });

  doc.setFontSize(14);
  doc.setFont('helvetica', 'normal');
  doc.text('Pro Forma Report', pageWidth / 2, 30, { align: 'center' });

  yPosition = 55;
  doc.setTextColor(51, 65, 85);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  const reportDate = new Date().toLocaleDateString('en-GB', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
  doc.text(`Report Date: ${reportDate}`, 14, yPosition);
  doc.text(`Tool: ${data.toolName}`, 14, yPosition + 6);

  yPosition += 20;

  doc.setTextColor(15, 23, 42);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Property Details', 14, yPosition);
  yPosition += 8;

  const inputRows = Object.entries(data.inputs).map(([key, value]) => [
    formatLabel(key),
    formatValue(value),
  ]);

  autoTable(doc, {
    startY: yPosition,
    head: [['Parameter', 'Value']],
    body: inputRows,
    theme: 'grid',
    headStyles: {
      fillColor: [30, 41, 59],
      textColor: [255, 255, 255],
      fontStyle: 'bold',
      fontSize: 11,
    },
    bodyStyles: {
      textColor: [51, 65, 85],
      fontSize: 10,
    },
    alternateRowStyles: {
      fillColor: [248, 250, 252],
    },
    margin: { left: 14, right: 14 },
  });

  yPosition = (doc as any).lastAutoTable.finalY + 15;

  if (yPosition > pageHeight - 60) {
    doc.addPage();
    yPosition = 20;
  }

  doc.setTextColor(15, 23, 42);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Financial Analysis', 14, yPosition);
  yPosition += 8;

  const outputRows = Object.entries(data.outputs).map(([key, value]) => [
    formatLabel(key),
    formatValue(value),
  ]);

  autoTable(doc, {
    startY: yPosition,
    head: [['Metric', 'Result']],
    body: outputRows,
    theme: 'grid',
    headStyles: {
      fillColor: [30, 41, 59],
      textColor: [255, 255, 255],
      fontStyle: 'bold',
      fontSize: 11,
    },
    bodyStyles: {
      textColor: [51, 65, 85],
      fontSize: 10,
    },
    alternateRowStyles: {
      fillColor: [248, 250, 252],
    },
    margin: { left: 14, right: 14 },
  });

  doc.setFillColor(30, 41, 59);
  doc.rect(0, pageHeight - 15, pageWidth, 15, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.text(
    'Generated by Property Launch Pad — propertylaunchpad.com',
    pageWidth / 2,
    pageHeight - 7,
    { align: 'center' }
  );

  const fileName = `${data.toolName.replace(/\s+/g, '_')}_${new Date().toISOString().split('T')[0]}.pdf`;
  doc.save(fileName);
}

function formatLabel(key: string): string {
  return key
    .replace(/([A-Z])/g, ' $1')
    .replace(/_/g, ' ')
    .split(' ')
    .map(word => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
    .join(' ')
    .trim();
}

function formatValue(value: any): string {
  if (value === null || value === undefined) {
    return 'N/A';
  }

  if (typeof value === 'boolean') {
    return value ? 'Yes' : 'No';
  }

  if (typeof value === 'number') {
    if (value > 1000 || value < -1000) {
      return new Intl.NumberFormat('en-GB', {
        minimumFractionDigits: 0,
        maximumFractionDigits: 2,
      }).format(value);
    }
    return value.toFixed(2);
  }

  if (typeof value === 'object') {
    return JSON.stringify(value);
  }

  return String(value);
}
