interface PDFData {
  toolName: string;
  inputs: Record<string, any>;
  outputs: Record<string, any>;
}

export function generateProFormaPDF(data: PDFData) {
  const printWindow = document.createElement('div');
  printWindow.id = 'print-content';
  printWindow.style.display = 'none';

  const reportDate = new Date().toLocaleDateString('en-GB', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  const inputRows = Object.entries(data.inputs)
    .map(([key, value]) => `
      <tr>
        <td class="px-4 py-2 border border-gray-300 font-medium">${formatLabel(key)}</td>
        <td class="px-4 py-2 border border-gray-300">${formatValue(value)}</td>
      </tr>
    `)
    .join('');

  const outputRows = Object.entries(data.outputs)
    .map(([key, value]) => `
      <tr>
        <td class="px-4 py-2 border border-gray-300 font-medium">${formatLabel(key)}</td>
        <td class="px-4 py-2 border border-gray-300">${formatValue(value)}</td>
      </tr>
    `)
    .join('');

  printWindow.innerHTML = `
    <style>
      @media print {
        body * {
          visibility: hidden;
        }
        #print-content, #print-content * {
          visibility: visible;
        }
        #print-content {
          position: absolute;
          left: 0;
          top: 0;
          width: 100%;
          display: block !important;
        }
        @page {
          margin: 20mm;
        }
      }
      #print-content {
        font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
        max-width: 800px;
        margin: 0 auto;
        padding: 20px;
        color: #1e293b;
      }
      .header {
        background-color: #1e293b;
        color: white;
        padding: 30px;
        text-align: center;
        margin-bottom: 30px;
      }
      .header h1 {
        font-size: 28px;
        font-weight: bold;
        margin: 0 0 10px 0;
      }
      .header p {
        font-size: 16px;
        margin: 0;
      }
      .meta-info {
        margin-bottom: 30px;
        color: #475569;
      }
      .section-title {
        font-size: 18px;
        font-weight: bold;
        margin: 30px 0 15px 0;
        color: #0f172a;
      }
      table {
        width: 100%;
        border-collapse: collapse;
        margin-bottom: 30px;
      }
      th {
        background-color: #1e293b;
        color: white;
        padding: 12px;
        text-align: left;
        font-weight: bold;
      }
      td {
        padding: 10px 12px;
        border: 1px solid #cbd5e1;
      }
      tr:nth-child(even) {
        background-color: #f8fafc;
      }
      .footer {
        background-color: #1e293b;
        color: white;
        padding: 15px;
        text-align: center;
        margin-top: 40px;
        font-size: 12px;
      }
    </style>

    <div class="header">
      <h1>Property Launch Pad</h1>
      <p>Pro Forma Report</p>
    </div>

    <div class="meta-info">
      <p><strong>Report Date:</strong> ${reportDate}</p>
      <p><strong>Tool:</strong> ${data.toolName}</p>
    </div>

    <h2 class="section-title">Property Details</h2>
    <table>
      <thead>
        <tr>
          <th>Parameter</th>
          <th>Value</th>
        </tr>
      </thead>
      <tbody>
        ${inputRows}
      </tbody>
    </table>

    <h2 class="section-title">Financial Analysis</h2>
    <table>
      <thead>
        <tr>
          <th>Metric</th>
          <th>Result</th>
        </tr>
      </thead>
      <tbody>
        ${outputRows}
      </tbody>
    </table>

    <div class="footer">
      Generated by Property Launch Pad — propertylaunchpad.com
    </div>
  `;

  document.body.appendChild(printWindow);

  setTimeout(() => {
    window.print();
    setTimeout(() => {
      document.body.removeChild(printWindow);
    }, 100);
  }, 100);
}

function formatLabel(key: string): string {
  return key
    .replace(/([A-Z])/g, ' $1')
    .replace(/_/g, ' ')
    .split(' ')
    .map(word => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
    .join(' ')
    .trim();
}

function formatValue(value: any): string {
  if (value === null || value === undefined) {
    return 'N/A';
  }

  if (typeof value === 'boolean') {
    return value ? 'Yes' : 'No';
  }

  if (typeof value === 'number') {
    if (value > 1000 || value < -1000) {
      return new Intl.NumberFormat('en-GB', {
        minimumFractionDigits: 0,
        maximumFractionDigits: 2,
      }).format(value);
    }
    return value.toFixed(2);
  }

  if (typeof value === 'object') {
    return JSON.stringify(value);
  }

  return String(value);
}
